### ISSUE TITLE
Request for Step-by-Step Deployment Guide

### ISSUE THREAD

**Issue by dasunhegoda** [sbidoul/runboat#98] opened 2023-09-06 12:19 UTC
Hello,

First of all, thank you for this fantastic project and for all the effort that has gone into making it.

I was wondering if there is a step-by-step deployment guide available? Such a guide would be extremely helpful for those of us looking to use this project but may not be completely familiar with all of its intricacies.

If a guide is available, could you please provide a link?

Thank you in advance for your time and assistance.

**Comment by dasunhegoda** [comment] 2023-09-07 11:03
<img width="900" alt="Screenshot 2023-09-07 at 4 33 01 PM" src="https://github.com/sbidoul/runboat/assets/2864612/378adaf6-fa66-47a3-a9fb-38a5cc4d39af">

I get the above error when I'm trying to run it.

**Comment by sbidoul** [comment] 2023-09-18 10:41
Maybe somme community members can help in this discussion. https://github.com/sbidoul/runboat/issues/98 
There are also indications in the wiki.

I'm closing this issue because it is not a bug.

**Closed** 2023-09-18 10:42 UTC

**Comment by tarteo** [comment] 2023-12-21 11:42
@dasunhegoda Had the same issue when using the example docker composer file. You just have to remove the commented lines from RUNBOAT_BUILD_ENV and other JSON formatted values.
