### ISSUE TITLE
Query Regarding Rancher Support and Deployment Guide

### ISSUE THREAD

**Issue by dasunhegoda** [sbidoul/runboat#97] opened 2023-09-06 07:52 UTC
Hello,

Firstly, thank you for this amazing project and all the hard work that has gone into it.

I'm interested in using it in an environment managed by Rancher and was wondering if this project is compatible with Rancher?

If it is, is there a deployment guide available specifically for Rancher setups? It would be really helpful to have some guidance on best practices and setup recommendations for deploying this project in a Rancher-managed environment.

Thanks in advance for your time and assistance.

**Comment by sbidoul** [comment] 2023-09-18 10:42
Runboat should work with any kubernetes distribution, including those from Rancher.

Maybe somme community members can help in this discussion. https://github.com/sbidoul/runboat/issues/98 
There are also indications in the wiki.

I'm closing this issue because it is not a bug nor a feature request.

**Closed by sbidoul** 2023-09-18 10:42 UTC
