### ISSUE TITLE
build failed during init_log

### ISSUE THREAD

**Issue by tafaRU** [sbidoul/runboat#28] opened 2021-11-29 15:01 UTC
The build https://runboat.odoo-community.org/webui/build.html?name=b16d2af42-3e08-4685-b865-873f184f0d72 related to https://github.com/OCA/l10n-italy/pull/2528 fails with the following error:

```
{"detail":"No log found."}
```

**Comment by sbidoul** [comment] 2021-11-29 20:37
A kubectl describe of the initialization pod shows

```
    State:          Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim: context canceled: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 01:00:00 +0100
      Finished:     Mon, 29 Nov 2021 15:41:18 +0100
```

This is likely due to disk performance issue we have on runbot3. microk8s has a [FAQ](https://microk8s.io/docs/troubleshooting#heading--common-issues) about this.

These issues should resolve themselves when  the new server with fast disks arrives.

So closing as this is most likely not a bug.

**Closed by sbidoul** 2021-11-29 20:37 UTC
